controller_manager:
  ros__parameters:
    update_rate: 30

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

# joint_broad:
#   ros__parameters:
#     use_sim_time: true

diff_cont:
  ros__parameters:
    odom_frame_id: odom
    base_frame_id: base_footprint

    left_wheel_names: ["lf_wheel_joint", "lb_wheel_joint"]
    right_wheel_names: ["rf_wheel_joint", "rb_wheel_joint"]
    wheel_separation: 0.162
    wheels_per_side: 1
    wheel_radius: 0.05
    enable_odom_tf: false
    open_loop: true
    position_feedback: false

    use_stamped_vel: false

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    publish_limited_velocity: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5
        min_velocity: -0.5
        # has_acceleration_limits: true
        # max_acceleration: 0.5
        # has_jerk_limits: true
        # max_jerk: 0.5
    # angular:
    #   z:
    #     has_velocity_limits: true
    #     max_velocity: 2.0
    #     min_velocity: -2.0
    # has_acceleration_limits: true
    # max_acceleration: 0.25
    # has_jerk_limits: true
    # max_jerk: 0.25
